### ISSUE TITLE
整理文件结构，做成 package（包） 的标准目录

### ISSUE THREAD

**Issue by peter-way** [sunpudding/python#10]
可参照文档 https://python-packaging.readthedocs.io/en/latest/
里面有个最简单的目录结构 https://python-packaging.readthedocs.io/en/latest/minimal.html

**Comment by sunpudding** [comment]
![qq 20180806175901](https://user-images.githubusercontent.com/37238869/43710530-7e5fe368-99a2-11e8-927f-26316b262234.jpg)
已对目录结构进行调整
