### ISSUE TITLE
应该算出 TCP 头的准确长度，由此知道 TCP 内容的开始位置。

### ISSUE THREAD

**Issue by peter-way** [sunpudding/python#2]
这里为什么是 66？
```
            # 进行判断后，写入此包应用层http数据
            if self.packet_len <= 66:
                self.packet_data.append("无HTTP报文")

```
如果 TCP 的内容恰好是 “无HTTP报文” 怎么办？
```
            if i != "无HTTP报文":
```

**Comment by sunpudding** [comment]
对于TCP头的长度计算，首先是在以太网的type中确定为IPV4协议，随后在IPV4协议中获取total length以及ihl，其两者的差值即为TCP包的长度，而在TCP的 Data offset字段中，我们可以得到TCP报头的长度，用TCP包的总长度减去TCP报头的长度，即为TCP下的应用层数据。

**Comment by peter-way** [comment]
没错，记得在 IPv4 中判断协议是 TCP 。

**Comment by sunpudding** [comment]
对此问题，已经加以修改
