### ISSUE TITLE
根据 python 文档修正类、函数及变量的名称

### ISSUE THREAD

**Issue by peter-way** [sunpudding/python#5]
应遵循 python 的命名方式，详见 https://www.python.org/dev/peps/pep-0008/

**Comment by sunpudding** [comment]
已对py文件的类、函数及变量的名称进行修正

**Comment by peter-way** [comment]
又冒出来一个 **typegather**
```
    def packet_ethernet_type(self, typegather=None):
```

**Comment by sunpudding** [comment]
参阅python库的一些源代码，发现别人都是采用小写的方式，对默认参数进行命名，在pep8中也没有看到对默认参数的具体要求，故此，对您提出的问题尚不明确

**Comment by peter-way** [comment]
若 **typegather** 是两个单词的话，应该参照该 py 文件的其他部分，改成 **typeGather**
