### ISSUE TITLE
应使用有意义的变量名，尤其是类变量、全局变量，或其他被多处引用的变量

### ISSUE THREAD

**Issue by peter-way** [sunpudding/python#7]
比如，以下代码的变量 **path1** , **path2** ，除非从源头逐条代码阅读，谁知道它是做什么的？这会增加阅读困难，不只是自己，还有同事。
```
    def __init__(self, path1, path2):
        """传入两个必填参数path1 path2"""
        self.path1 = path1
        self.path2 = path2
```

前面有个 issue 提到类、方法、变量的命名规则，这些都是为了降低人与人之间的沟通成本，我们要追求简洁、明了的代码，让人一看类名、方法名、变量名便知它的大概功能、意义。这需要时间练习，多多留意。

**Comment by sunpudding** [comment]
此问题以后会多多留意，有不合适的地方，还请大神多多指导^-^

**Comment by sunpudding** [comment]
该问题，已做修改
 def __init__(self, pcapath, httpfile):
        """传入两个必填参数path1 path2"""
        self.pcapath = pcapath
        self.httpfile = httpfile
